### ISSUE TITLE
Want to work together?

### ISSUE THREAD

**Issue by azy2** [barcodebunny/elden-ring-cheat-sheet#8]
Hello. We have a similar project well in the works over at https://github.com/RoundtableHold/roundtablehold.github.io
Our site is https://roundtablehold.net/ if you want to check it out.

I was wondering if you wanted to come collaborate on our project in order to avoid duplicating work? We're trying to build a huge community driven site for Elden Ring and would love to work with you.

**Comment by barcodebunny** [comment]
Ooooh, this is far more fleshed out than mine. I had really only intended to use this myself, and having it be useful for the greater community was more incidental, but I'm glad that people have found it helpful. 
I'd definitely offer to help with roundtable, as well. Though it seems like it's a fair bit beyond this project already, ahah.
I've found the community Discord, so I'll come along there, for sure!
